name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Check formatting
        run: deno fmt --check main.js

      - name: Lint
        run: deno lint main.js

      - name: Typecheck
        run: deno check main.js
